LOG-1874: lokistack-gateway component restarting too many times on OpenShift
ViaQ/loki-operator pull request #100
Opened 2021-10-27 07:44 UTC by sasagarw

This PR:
- fixes serviceAccount issue of gateway for static, dynamic modes. Currently, we were setting ServiceAccountName for all the 3 modes but this is not correct as we don't create any ServiceAccount for static and dynamic modes. Hence the deployment errors out saying missing ServiceAccountName and a reconcile error occurs. Hence moved this to openshift specific deployment configuration (this was done in #101)
- degraded condition on the lokistack was getting set but the deployments were still taking places because of the non-nil error returned by `SetDegradedCondition` function.
- fixed the `uuid` and `cookieSecret` issue by fetching the existing tenants.yaml configuration and using the same value in subsequent reconcile. Both uuid and cookieSecret will be created only once.

/cc @periklis 

### Links
- Jira: https://issues.redhat.com/browse/LOG-1874

2021-11-22 05:15 UTC, sasagarw commented
@periklis can we do same with the `cookieSecret` as well?

2021-11-25 15:16 UTC, periklis requested changes
Looks good, only a couple of small improvements required.

2021-11-25 15:16 UTC, periklis commented on bundle/manifests/loki-operator.clusterserviceversion.yaml
> +  name: loki-operator.v0.1.98
Can we drop this random version please?

2021-11-25 15:16 UTC, periklis commented on bundle/manifests/loki-operator.clusterserviceversion.yaml
> +                imagePullPolicy: Always
Same here please keep the old defaults

2021-11-25 15:16 UTC, periklis commented on internal/handlers/internal/gateway/tenant_configmap.go
> +	tcmMap := make(map[string]map[string]string)
Suggest to make the inside map a small struct, e.g. `tenantData`

2021-11-26 10:00 UTC, periklis approved these changes

2021-11-26 10:00 UTC, merged