LOG 1838: Adding Promtail and Openshift Logging docs
ViaQ/loki-operator pull request #104
Opened 2021-11-15 20:10 UTC by Red-GV

This PR adds documentation for using the Promtail and Openshift-Logging forwarder for sending logs into the gateway.

JIRA: https://issues.redhat.com/browse/LOG-1838

2021-11-16 04:26 UTC, sasagarw requested changes
Looks good in general. One missing bits I see is to add what should we expect to see after we have applied this `hack/promtail_client.yaml`. A short paragraph or some kubectl commands which will show us the deployment so that we know what is expected to happen after this.

2021-11-16 04:26 UTC, sasagarw commented on docs/forwarding_logs_to_gateway.md
> +__Please read the `hacking_loki_operator.md` document before proceeding with the following instructions.__
Linking the document link would be good here.
```suggestion
__Please read the [hacking_loki_operator.md](https://github.com/ViaQ/loki-operator/blob/master/docs/hack_loki_operator.md) document before proceeding with the following instructions.__
```

2021-11-16 04:26 UTC, sasagarw commented on docs/forwarding_logs_to_gateway.md
> +2. Execute the following commands in the terminal:
```suggestion
2. Execute the following command in the terminal:
```

2021-11-16 10:43 UTC, periklis requested changes
This PR is not sufficiently matching the task's acceptance criteria:
1. Regardless OpenShift Logging, we should add a section for configuring fluentd with the grafana fluentd loki plugin to visualize how to achieve a similar behavior.
2. The manifests should not be put into the hack folder. This nurtures the expectation that these manifests are actively maintained in addition to the lokistack/loki-operator. Please add any manifests inline in splitting them per manifest and adding some description on why we need this and where to put attention on customization.
3. For better visualization the entrypoint site should like to two different guides one for fluentd and one for promtail, because the manifests are quite noisy.

2021-11-17 07:53 UTC, periklis commented on docs/forwarding_logs_to_gateway.md
> +# Forwarding Logs to Loki Operator
Suggest `Forwardig logs to LokiStack`

2021-11-17 07:53 UTC, periklis commented on docs/forwarding_logs_to_gateway.md
> +This document will describe how to send application, infrastructure, and audit logs to the Lokistack Gateway as different tenants using Promtail. The gateway provides secure access to the distributor
`Using Promtail or Fluentd`

2021-11-17 07:53 UTC, periklis commented on docs/forwarding_logs_to_gateway.md
> +This document will describe how to send application, infrastructure, and audit logs to the Lokistack Gateway as different tenants using Promtail. The gateway provides secure access to the distributor
`The built-in gateway provides..`

2021-11-17 07:53 UTC, periklis commented on docs/forwarding_logs_to_gateway.md
> +
`in the Promtail and Fluentd sections`

2021-11-17 07:53 UTC, periklis commented on docs/forwarding_logs_to_gateway.md
> +1. Deploy the Loki Operator and an `lokistack` instance with the gateway enabled.
Need to precise what `with the gateway enabled` means, i.e. your operator should run with the appropriate feature flags.

2021-11-17 07:53 UTC, periklis commented on docs/forwarding_logs_to_gateway.md
> +  name: "kube:admin"
I suggest to drop the `kube:admin` user here. It is a temporary user account that is usually dropped after configuring IDP on k8s.

2021-11-17 07:53 UTC, periklis commented on docs/forwarding_logs_to_gateway.md
> +### Log Entries Out of Order
This depends highly on the t-shirt size you pick. IIRC `1x.medium` can handle `IngestionRate: 10` and `IngestionBurstSize: 20`. Right?

2021-11-23 04:03 UTC, sasagarw requested changes
Looks good. However, I still miss the step-by-step guide to use OpenShift Logging ClusterLogForwarder part which is mentioned in AC of this task. Have we updated the AC?

2021-11-23 06:49 UTC, periklis commented on index.md
> +* The [forwarding_logs_to_gateway.md](https://github.com/ViaQ/loki-operator/tree/master/docs/forwarding_logs_to_gateway.md) document provides instructions for configuring forwarding clients to ship l
Yes that would make it easier to identify the client.

2021-11-23 12:59 UTC, Red-GV commented
@sasagarw The problem is that we currently do not have a path in with the ClusterLogForwarder because it currently does not support using the bearer token for authorization. I could toss in what it would look like in theory, but currently we can't actually use it yet.

2021-11-24 09:05 UTC, periklis approved these changes
LGTM

2021-11-24 09:05 UTC, merged